apiVersion: opa.k8smgmt.io/v3
kind: OPAPolicy
metadata:
  name: bp-reliability
  project: kubeflow-mks
spec:
  constraintList:
  - name: disallowed-tags-custom
    version: v1
  - name: replica-limits-custom
    version: v1
  - name: required-annotations-custom
    version: v1
  - name: required-labels-custom
    version: v1
  - name: required-probes-custom  
    version: v1
  sharing:
    enabled: true
    projects:
    - name: kubeflow-mks
  version: v1