apiVersion: opa.k8smgmt.io/v3
kind: OPAPolicy
metadata:
  name: bp-security
  project: kubeflow-mks
spec:
  constraintList:
  - name: allowed-repos-custom
    version: v1
  - name: block-nodeport-services-custom
    version: v1
  - name: https-only-custom
    version: v1
  - name: image-digests-custom
    version: v1
  sharing:
    enabled: true
    projects:
    - name: kubeflow-mks
  version: v1