apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: allowed-repos-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/allowed-repos-custom/allowed-repos.yaml
    options: {}
    type: Yaml

