apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: replica-limits-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/replica-limits-custom/replica-limits.yaml
    options: {}
    type: Yaml

