apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: required-labels-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/required-labels-custom/required-labels.yaml
    options: {}
    type: Yaml

