apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: seccomp-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/seccomp-custom/seccomp.yaml
    options: {}
    type: Yaml

