apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: allowed-users-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/allowed-users-custom/allowed-users.yaml
    options: {}
    type: Yaml
  published: true  
  templateName: allowed-users-custom
  version: v1