apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: disallowed-tags-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/disallowed-tags-custom/disallowed-tags.yaml
    options: {}
    type: Yaml
  published: true 
  templateName: disallowed-tags-custom
  version: v1