apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: forbidden-sysctls-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/forbidden-sysctls-custom/forbidden-sysctls.yaml
    options: {}
    type: Yaml
  published: true 
  templateName: forbidden-sysctls-custom
  version: v1