apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: host-namespace-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/host-namespace-custom/host-namespace.yaml
    options: {}
    type: Yaml
  published: true  
  templateName: host-namespace-custom
  version: v1