apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: https-only-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/https-only-custom/https-only.yaml
    options: {}
    type: Yaml
  published: true  
  templateName: https-only-custom
  version: v1