apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: replica-limits-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/replica-limits-custom/replica-limits.yaml
    options: {}
    type: Yaml
  published: true 
  templateName: replica-limits-custom
  version: v1