apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraint
metadata:
  labels:
    rafay.dev/opa: constraint
  name: seccomp-custom
  project: kubeflow-mks
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/seccomp-custom/seccomp.yaml
    options: {}
    type: Yaml
  published: true 
  templateName: seccomp-custom
  version: v1